#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: ForeWord # REQUIRED - Enter your app name
  ios_id: 1443681527 # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: com.walkingriver.foreword # Optional - Enter Android app id like: com.example.app

  icon: images/icon-512.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  favicon: images/favicon.png # uncomment if uploading own favicon
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-favicon.png - can be .ico or .png
  # 16px or greater, square

  # Leave blank to auto-magically populate
  #screenshot: images/app-screen-640x1136.png
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

  #video: # uncomment if prefer to show a video preview in the screen instead of image
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-preview.mp4
  # 640x1136px

  #app_twitter: # uncomment if the app has a twitter account "@my-awesome-app"
  creator_twitter: walkingriver # uncomment if creator has a twitter account "@awesome-dev"
  social_image: /images/icon-512.png # uncomment and add an image - defaults to icon
  # This will show up when your url is shared on sites like facebook and twitter
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-social_image.png
  # 512px or greater, square or width = 2X height
#
# Marketing
#
marketing_header: A Challenging Word Square Game - Now more than 9000 puzzles! # Optional
marketing_desc: <p>Word Squares are a special type of word puzzle, consisting of words that can be read both horizontally and vertically. A true word square is made up of exactly four words, such as in this example...</p><table class="square"><tr><td>s</td><td>w</td><td>i</td><td>m</td></tr><tr><td>w</td><td>a</td><td>d</td><td>e</td></tr><tr><td>i</td><td>d</td><td>e</td><td>s</td></tr><tr><td>m</td><td>e</td><td>s</td><td>a</td></tr></table><p>There are literally hundreds of valid combinations of words, which could keep you occupied for months. But what fun is that? While not a true word square, we can also construct valid puzzles of eight words, as in this example...</p><table class="square"><tr><td>m</td><td>i</td><td>n</td><td>t</td></tr><tr><td>a</td><td>r</td><td>i</td><td>a</td></tr><tr><td>s</td><td>o</td><td>c</td><td>k</td></tr><tr><td>k</td><td>n</td><td>e</td><td>e</td></tr></table><p>Foreword offers you 3x3 and 4x4 word puzzles in more than 9000 combinations. Play 2-3 times per day to challenge your wits and exercise your brain, for potentially years of gameplay.</p><p>And coming soon, we'll add 5x5 grids, for hundreds of more puzzles.</p>

#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github:
  facebook: 
  twitter: walkingriver
  pinterest:
  instagram: walkingriver
  email: michael@walkingriver.com
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-silver-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#989898" # Optional
background_image: /images/backgrounds/green-bg.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: ForeWord # Optional - Enter your site title
description:  # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - REAMDE-old.md
